project-config:
  env: production
  config-name: application-production.yml

# mybatis-plus:
#   configuration:
#     log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# 生产环境禁用 Swagger 文档
springdoc:
  api-docs:
    enabled: false
